/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "agenda.h"

bool_t
xdr_param (XDR *xdrs, param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombre_apellido, MAXIMO))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->edad))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ciudad, MAXIMO))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_array_registro (XDR *xdrs, array_registro *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->registros.registros_val, (u_int *) &objp->registros.registros_len, MAXimo,
		sizeof (registro), (xdrproc_t) xdr_registro))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_devuelta))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_parametros_b (XDR *xdrs, parametros_b *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->provincia, MAXIMO))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->edad))
		 return FALSE;
	return TRUE;
}
