/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "agenda.h"

array_registro *
buscar_apellido_1_svc(char **argp, struct svc_req *rqstp)
{
	static array_registro  result;

	/*
	 * insert server code here
	 */

	return &result;
}

array_registro *
buscar_provincia_1_svc(parametros_b *argp, struct svc_req *rqstp)
{
	static array_registro  result;

	/*
	 * insert server code here
	 */

	return &result;
}
