/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AGENDA_H_RPCGEN
#define _AGENDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIMO 20

struct param {
	char *nombre_apellido;
	int edad;
	char *ciudad;
};
typedef struct param param;

struct array_registro {
	struct {
		u_int registros_len;
		registro *registros_val;
	} registros;
	int cant_devuelta;
};
typedef struct array_registro array_registro;

struct parametros_b {
	char *provincia;
	int edad;
};
typedef struct parametros_b parametros_b;

#define AGENDA 0x30000003
#define AGENDA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define buscar_apellido 1
extern  array_registro * buscar_apellido_1(char **, CLIENT *);
extern  array_registro * buscar_apellido_1_svc(char **, struct svc_req *);
#define buscar_provincia 2
extern  array_registro * buscar_provincia_1(parametros_b *, CLIENT *);
extern  array_registro * buscar_provincia_1_svc(parametros_b *, struct svc_req *);
extern int agenda_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define buscar_apellido 1
extern  array_registro * buscar_apellido_1();
extern  array_registro * buscar_apellido_1_svc();
#define buscar_provincia 2
extern  array_registro * buscar_provincia_1();
extern  array_registro * buscar_provincia_1_svc();
extern int agenda_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);
extern  bool_t xdr_array_registro (XDR *, array_registro*);
extern  bool_t xdr_parametros_b (XDR *, parametros_b*);

#else /* K&R C */
extern bool_t xdr_param ();
extern bool_t xdr_array_registro ();
extern bool_t xdr_parametros_b ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AGENDA_H_RPCGEN */
