/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "agenda.h"


void
agenda_1(char *host)
{
	CLIENT *clnt;
	array_registro  *result_1;
	char * buscar_apellido_1_arg;
	array_registro  *result_2;
	parametros_b  buscar_provincia_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, AGENDA, AGENDA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = buscar_apellido_1(&buscar_apellido_1_arg, clnt);
	if (result_1 == (array_registro *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = buscar_provincia_1(&buscar_provincia_1_arg, clnt);
	if (result_2 == (array_registro *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	agenda_1 (host);
exit (0);
}
